#!/usr/bin/python

import os

def fFox(private):
  if private in ['firefox', 'private']:
    os.system('firefox-esr --private-window')
  return private
  
def main():
  print('')
  enter = raw_input(">> ")
  fFox(enter)
  
if __name__ == '__main__':
  main()
